spring:
  thymeleaf:
    prefix:
      - classpath:/static/
      - classpath:/templates/members/
      - classpath:/templates/fragments
      - classpath:/templates/login/
      - classpath:/templates/posts/
      - classpath:/templates/comments/
      - classpath:/templates/
    suffix: .html

  env:
    google.client.id: ${{ secrets.GOOGLE_CLIENT_ID}}
    google.client.pw: ${{ secrets.GOOGLE_CLIENT_PW}}
    naver.client.id: ${{ secrets.NAVER_CLIENT_ID}}
    naver.client.secret: ${{ secrets.NAVER_CLIENT_SECRET}}


  datasource:
    #
    url: jdbc:h2:tcp://localhost/~/BlogAlarm
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.trace: trace
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
