spring:

  thymeleaf:
    prefix:
      - classpath:/static/
      - classpath:/templates/members/
      - classpath:/templates/fragments/
      - classpath:/templates/login/
      - classpath:/templates/posts/
      - classpath:/templates/comments/
      - classpath:/templates/
    suffix: .html
  datasource:
    url: ${DATABASE_URL}
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      format_sql: true
      default_batch_fetch_size: 100

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    pw: ${GOOGLE_CLIENT_PW}

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    url: ${NAVER_REDIRECT_URL}

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.trace: trace
